### PR TITLE
Migrate to spring boot using maven

### PR DESCRIPTION
**Pull request by charelsm111**
Hello @jchacana,

I made changes in order to migrate to spring boot apps using maven.

### CODE REVIEW

**Review by jchacana — COMMENTED** [review]
Hey Charel.
So far, by looking at your code at this moment, it loos pretty good to me. No major issues at all.
Now on the minor issues:

- How are you keeping old functionality to load a csv with data? 
- About the tests, there are some issues when running them in IntelliJ, directly from the IDE instead of running them on the command line. I get a couple of "JUnit Vintage" tests failing, whereas when running from the command line, evertyhing looks good.

**Comment by charelsm111** [comment]
Hi @jchacana, Thank you for the review.

Here's the revision:
1. Fix the junit vintage error, the cause was because I used runner class which belongs to junit 4.
2. For load csv file and persist it to database I use a runner class as a @component and add AccountCsvService to handle creation and check if the record is exists.

**Comment by jchacana** [comment]
> Hi @jchacana, Thank you for the review.
> 
> Here's the revision:
> 
> 1. Fix the junit vintage error, the cause was because I used runner class which belongs to junit 4.
> 2. For load csv file and persist it to database I use a runner class as a @component and add AccountCsvService to handle creation and check if the record is exists.

Verified 1. For number 2, still not clear how. Update your README accordingly. By looking at your code I  see that the file must reside in a hardcoded location. 
Think of this use case: Start the app with preexisting data from a csv file, starting it from a jar file. Should I open the jar file in order to modify the starting csv? If I do that, and the jar is signed (for example), it gets invalidated because the binary was modified. Consider that.

**Comment by charelsm111** [comment]
Hi @jchacana ,

I provided account upload page to add more accounts via csv file. The upload page will be root, but you can skip to login page because I provided 2 default accounts. I also updated the readme.md according to the changes.

**Review by jchacana — APPROVED** [review]

**Comment by jchacana** [comment]
Ok we're good. Move on to the next stage

**Pull request merged**
